name: QG
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.18
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - matplotlib=3.5.3
  - tqdm=4.66.1
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - scikit-learn=1.3.2
  - torch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - pytorch-lightning=2.1.3
  - cartopy=0.21.1
